name: Create uber-jar and publish on Github Packages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Create Uber jar
      id: create_uber
      run: ./gradlew :aws:shadowJar 
    - name: version
      run: echo "::set-output name=version::$(./gradlew :aws:printVersion)"
      id: version   
    - name: Create release and attach uber jar
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        #automatic_release_tag: "latest"
        automatic_release_tag: "aws_${{ steps.version.outputs.version }}"
        prerelease: true
        title: "AWS uber jar ${{ steps.version.outputs.version }}"
        files: ./aws/build/libs/*-uber.jar
  